### ISSUE TITLE
ibm_kms_key resource to create or update key policies in Terraform has been deprecated

### ISSUE THREAD

**Issue by ElectricToaster7** [cloud-native-toolkit/terraform-ibm-kms-key#13]
Hello, had a customer ask if we will be updating the module to support the policies being defined through 
resource "ibm_kms_key_policies" instead of applied directly within the resource "ibm_kms_key" as there is now a 45 day notice 

https://cloud.ibm.com/notifications?selected=1641934980107
The ability to use the ibm_kms_key resource to create or update key policies in Terraform has been deprecated in favor of a dedicated ibm_kms_key_policies resource. This deprecation will last 45 days, at which time only the ibm_kms_key_policies resource can be used to update policies.
In the meantime, either ibm_kms_key or ibm_kms_key_policies can be used to manage key policies. However, use only one resource or the other, ensuring that you migrate to the ibm_kms_key_policies resource at the end of 45 days. For more information, check out the Terraform documentation: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/kms_key#example-usage-to-provision-kms-key-with-key-policies

**Comment by emaadparacha** [comment]
Replying here to see if there's any update on this?
